
export const COMMON = {
  	SERVER_REQUEST: 'SERVER_REQUEST',
  	SERVER_FAILURE: 'SERVER_FAILURE',
  	SERVER_SUCCESS: 'SERVER_SUCCESS',
}

export const AUTH = {
	CHECK_AUTH: 'CHECK_AUTH',
	LOGGED_IN: 'LOGGED_IN',
	LOGGED_OUT: 'LOGGED_OUT',
	UPDATE_USER: 'UPDATE_USER',
}

export const JOB = {
	SET_COMPLETED_JOBS: 'SET_COMPLETED_JOBS',
	SET_LATEST_JOBS: 'SET_LATEST_JOBS',
}

export const REVIEW = {
	SET_REVIEWS: 'SET_REVIEWS',
}

export const MEMBER = {
	SET_STAFF_MEMBERS: 'SET_STAFF_MEMBERS',
}
